### ISSUE TITLE
ImportError: No module named pyasn1

### ISSUE THREAD

**Issue by sunny0day** [cle0patra/burp-jwt-extension#7]
Hi! I'm excited to use your JWT fuzzer, but have trouble getting it to run. Here's the stack trace:

```
Traceback (most recent call last):
  File "/opt/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py", line 51, in <module>
    import pyasn1
ImportError: No module named pyasn1

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx5.f$0(/opt/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py:592)
	at org.python.pycode._pyx5.call_function(/opt/burp-jwt-fuzzhelper-extension/burp-jwt-fuzzhelper.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at burp.dho.<init>(Unknown Source)
	at burp.hs.a(Unknown Source)
	at burp.ge3.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The directory `/usr/lib/python2.7/dist-packages/pyasn1` exists and the `/usr/lib/python2.7/dist-packages` path has been added to the Python environment settings in Burp.

Maybe you have an idea what's going on?

**Comment by sunny0day** [comment]
Ha, solved it already. I did the following:

```
pip install --upgrade pip
pip install pyasn1 --ignore-installed
```
